version: "3"
services:
    app:
        container_name: app
        restart: always
        build: ./client/
        ports:
            - 5000:5000
        links:
            - api
        environment: 
            - HOST=0.0.0.0
        volumes:
            - ./client:/code    
    api:
        container_name: api
        restart: always
        build: ./server/
        ports:
            - 8081:8081
        links:
            - mongo
        volumes:
            - ./server:/code

    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - db-data:/data/db
            - mongo-config:/data/configdb
        ports:
            - 27017:27017

volumes:
    db-data:
    mongo-config: